require('dotenv').config({path:'./.env'})
const express = require('express')
const router = require('./routes/router')
require('./db/db_connect')
const PORT = 3000 || process.env.PORT
const app = express()
app.set('view engine', 'ejs')
app.use(express.json())
app.use(router)
app.listen(PORT, () => console.log("server is up at "+PORT))